name: Amnesia
on: workflow_dispatch

env:
  NAME: Luigi

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: "Dis bonjour"
        if: ${{ env.NAME != 'Luigi'}}
        run: echo "Salut, vous n'etes pas Luigi ?! "
      - name: "Hello Luigi"
        if: ${{ env.NAME == 'Luigi'}}
        run: echo "Salut $NAME, ravi de vous revoir"
